/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.wiloon.java21;

import java.util.Random;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        double Pi = calcPi();
        System.out.println(Pi);
        return "";
    }

    public static double calcPi() {
        int totalPoints = 1000000000;
        int insideCircle = 0;

        Random random = new Random();
        for (long i = 0; i < totalPoints; i++) {
            double x = random.nextDouble() * 2 - 1;
            double y = random.nextDouble() * 2 - 1;
            if (x * x + y * y <= 1) {
                insideCircle++;
            }
        }
        double pi = 4.0 * insideCircle / totalPoints;
        return pi;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
