/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.5/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    //implementation(libs.guava)
}

testing {
    suites {
        getByName<JvmTestSuite>("test") {
            useJUnitJupiter("5.10.0")
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_26
    targetCompatibility = JavaVersion.VERSION_26
}

application {
    // Default main; override: ./gradlew run -PmainClass=com.wiloon.playground.RunnableDemo
    mainClass.set(
        providers.gradleProperty("mainClass")
            .orElse("com.wiloon.playground.SamDemo")
            .get()
    )
}
