/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.wiloon.playground;

import java.util.Random;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class App {
    private static final int DEFAULT_PI_SAMPLES = 1_000_000_000;
    private static final int GREETING_PI_SAMPLES = 10_000;

    public String getGreeting() {
        double pi = calcPi(new Random(), GREETING_PI_SAMPLES);
        System.out.println(pi);
        return "";
    }

    public static double calcPi() {
        return calcPi(new Random(), DEFAULT_PI_SAMPLES);
    }

    static double calcPi(Random random, int totalPoints) {
        int insideCircle = 0;

        for (int i = 0; i < totalPoints; i++) {
            double x = random.nextDouble() * 2 - 1;
            double y = random.nextDouble() * 2 - 1;
            if (x * x + y * y <= 1) {
                insideCircle++;
            }
        }
        return 4.0 * insideCircle / totalPoints;
    }

    public static void main(String[] args) {
        int threadCount = 3;
        ExecutorService es = Executors.newFixedThreadPool(threadCount);
        for (int i = 0; i < threadCount; i++) {
            es.execute(
                    new Runnable() {
                        @Override
                        public void run() {
                            System.out.println(new App().getGreeting());
                        }
                    });
        }
        es.shutdown();
    }
}
